

import  Heder  from "../home/Heder";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className="h-screen w-full" >
      <Heder/>
        {children}
      </div>
  )
}
