import { Inter } from "next/font/google";
import Heder from "./Heder";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "admin-land-mark",
  description: "Generated by admin-land-mark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Heder />
      {children}
    </div>
  );
}
